### PR TITLE
Added Parsing option for testing a single Systemd-service

### PR DESCRIPTION
**Pull request by Stunkymonkey**
added new option via -s
to check a single service
Example: 

```
bin/pynagsystemd.py -s syslog
SYSTEMD OK
```

### CODE REVIEW

**Comment by kbytesys** [comment]
optparse is deprecated. In this weekend I will accept the pr, but I will change it to argparse.

**Comment by Stunkymonkey** [comment]
Okay fine
Thanks in advance

**Comment by Stunkymonkey** [comment]
i changed it to argparse, like you want it

**Comment by kbytesys** [comment]
Thank you!

**Pull request merged**
